#!/bin/bash
# =================================================================
# JETSON FULL DEPLOYMENT SCRIPT - TFM Navigation System
# Sync completo: Mac → Jetson con validación automática
# =================================================================

set -e  # Exit on any error

# Configuration
JETSON_IP="${JETSON_IP:-192.168.8.204}"
JETSON_USER="${JETSON_USER:-aria}"
JETSON_PATH="~/jetson-aria"
LOCAL_SRC="./src"

echo "🚀 JETSON FULL DEPLOYMENT - TFM Navigation System"
echo "================================================================="
echo "📱 Mac (Master) → 🤖 Jetson (Worker)"
echo "Target: ${JETSON_USER}@${JETSON_IP}:${JETSON_PATH}"
echo "================================================================="

# Verificar que estamos en el directorio correcto
if [[ ! -d "src" ]]; then
    echo "❌ Error: No se encuentra directorio 'src/'"
    echo "💡 Ejecutar desde ~/aria-navigation-tfm/"
    exit 1
fi

# Verificar arquitectura Clean
if [[ ! -d "src/core" ]] || [[ ! -d "src/utils" ]]; then
    echo "❌ Error: Estructura Clean Architecture no encontrada"
    echo "💡 Verificar que existe src/core/ y src/utils/"
    exit 1
fi

echo "✅ Estructura Mac validada"

# Test conexión Jetson
echo "🔍 Testing conexión con Jetson..."
if ! ssh -o ConnectTimeout=5 ${JETSON_USER}@${JETSON_IP} "echo 'Conexión OK'" > /dev/null 2>&1; then
    echo "❌ Error: No se puede conectar al Jetson"
    echo "💡 Verificar: ssh ${JETSON_USER}@${JETSON_IP}"
    exit 1
fi
echo "✅ Conexión Jetson OK"

# Crear estructura en Jetson
echo "📁 Creando estructura en Jetson..."
ssh ${JETSON_USER}@${JETSON_IP} "
    mkdir -p ${JETSON_PATH}/{src,logs,models}
    echo '✅ Estructura Jetson creada'
"

# Sync código fuente completo
echo "📦 Sincronizando código fuente..."
rsync -avz --delete \
    --exclude="__pycache__" \
    --exclude="*.pyc" \
    --exclude=".git" \
    --exclude="logs/*" \
    ${LOCAL_SRC}/ ${JETSON_USER}@${JETSON_IP}:${JETSON_PATH}/src/

echo "✅ Código sincronizado"

# Copiar archivos de configuración
echo "⚙️  Copiando configuración..."
if [[ -f "utils/config.py" ]]; then
    scp utils/config.py ${JETSON_USER}@${JETSON_IP}:${JETSON_PATH}/src/utils/
fi

# Generar jetson_server.py automáticamente
echo "🤖 Generando jetson_server.py..."
cat > /tmp/jetson_server.py << 'EOF'
#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
JETSON SERVER - Auto-generated by jetson_deploy.sh
TFM Navigation System - Jetson Worker Node

Receives frames from Mac via ImageZMQ → Processes with Clean Architecture → Sends dashboard back
"""

import os
import sys
import time
import signal
import socket
import struct
import threading
import cv2
import numpy as np
from typing import Optional

# Add src to Python path
sys.path.append(os.path.join(os.path.dirname(__file__), 'src'))

# Import Clean Architecture components
try:
    from core.navigation.builder import build_navigation_system
    from utils.config import Config
    from utils.ctrl_handler import CtrlCHandler
except ImportError as e:
    print(f"❌ Import Error: {e}")
    print("💡 Verificar que el código se sincronizó correctamente")
    sys.exit(1)

class JetsonServer:
    """Jetson Worker Node - Processes frames from Mac"""
    
    def __init__(self):
        self.coordinator = None
        self.running = False
        self.stats = {
            'frames_processed': 0,
            'processing_time': 0.0,
            'start_time': time.time()
        }
        
        # Setup signal handling
        self.ctrl_handler = CtrlCHandler()
        
        print("🤖 JETSON SERVER - TFM Navigation System")
        print("=" * 50)
        
    def setup_coordinator(self):
        """Initialize navigation coordinator with Clean Architecture"""
        try:
            print("🏗️  Inicializando Clean Architecture...")
            self.coordinator = build_navigation_system(enable_dashboard=False)
            print("✅ Coordinator inicializado")
            return True
        except Exception as e:
            print(f"❌ Error inicializando coordinator: {e}")
            return False
    
    def test_components(self):
        """Test individual components"""
        print("🧪 Testing components...")
        
        # Test Builder
        try:
            from core.navigation.builder import build_navigation_system
            coordinator = build_navigation_system(enable_dashboard=False)
            print("✅ Builder: OK")
        except Exception as e:
            print(f"❌ Builder Error: {e}")
            return False
        
        # Test YOLO
        try:
            test_frame = np.random.randint(0, 255, (480, 640, 3), dtype=np.uint8)
            detections = coordinator.yolo_processor.process_frame(test_frame, None)
            print(f"✅ YOLO: OK ({len(detections)} test detections)")
        except Exception as e:
            print(f"❌ YOLO Error: {e}")
            return False
        
        # Test Audio
        try:
            coordinator.audio_system.speak_force("Test audio system")
            print("✅ Audio: OK")
        except Exception as e:
            print(f"❌ Audio Error: {e}")
            return False
        
        print("✅ All components OK")
        return True
    
    def start_server(self):
        """Start ImageZMQ server to receive frames from Mac"""
        if not self.setup_coordinator():
            return False
        
        print("🔗 Starting ImageZMQ server...")
        print("📡 Waiting for Mac connection on port 5555...")
        
        # TODO: Implement ImageZMQ communication
        # This will be completed in Phase 3
        
        self.running = True
        try:
            while self.running and not self.ctrl_handler.should_stop:
                # Placeholder for ImageZMQ processing
                time.sleep(0.1)
                
        except KeyboardInterrupt:
            print("\n🛑 Interrupt detected")
        finally:
            self.cleanup()
    
    def cleanup(self):
        """Cleanup resources"""
        print("🧹 Cleaning up...")
        if self.coordinator:
            try:
                self.coordinator.cleanup()
            except:
                pass
        print("✅ Cleanup complete")

def main():
    """Main entry point"""
    import sys
    
    server = JetsonServer()
    
    if len(sys.argv) > 1:
        if sys.argv[1] == "test-components":
            success = server.test_components()
            sys.exit(0 if success else 1)
        elif sys.argv[1] == "test":
            print("🧪 Basic test mode")
            success = server.setup_coordinator()
            print("✅ Setup OK" if success else "❌ Setup Failed")
            sys.exit(0 if success else 1)
    
    # Default: start server
    server.start_server()

if __name__ == "__main__":
    main()
EOF

# Copiar jetson_server.py al Jetson
scp /tmp/jetson_server.py ${JETSON_USER}@${JETSON_IP}:${JETSON_PATH}/
rm /tmp/jetson_server.py

# Hacer ejecutable
ssh ${JETSON_USER}@${JETSON_IP} "chmod +x ${JETSON_PATH}/jetson_server.py"

echo "✅ jetson_server.py generado"

# Verificar deployment
echo "🔍 Verificando deployment..."
ssh ${JETSON_USER}@${JETSON_IP} "
    cd ${JETSON_PATH}
    echo '📁 Estructura:'
    ls -la
    echo ''
    echo '📦 Código sincronizado:'
    find src -name '*.py' | wc -l | xargs echo 'Archivos Python:'
    echo ''
    echo '🧪 Test rápido:'
    python3 jetson_server.py test
"

echo ""
echo "🎉 DEPLOYMENT COMPLETO"
echo "================================================================="
echo "✅ Código Mac → Jetson sincronizado"
echo "✅ jetson_server.py generado y funcional"
echo "✅ Clean Architecture validada en Jetson"
echo ""
echo "🚀 Próximos pasos:"
echo "   1. ssh ${JETSON_USER}@${JETSON_IP}"
echo "   2. cd ${JETSON_PATH}"
echo "   3. python3 jetson_server.py test-components"
echo "================================================================="